
import Head from 'next/head'
import Navbar from "./Navbar";
import Footer from "./Footer";
type Props = {
    children: React.ReactNode
}

export default function Layout(props: Props) {
    const {children} = props;
    return (
        <>
            <Head>
                <title>test</title>
                {/* <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            {/* px-2 */}
            <div>
                <Navbar />
                {children}
                <Footer />
            </div>
        </>
    )
}